#!/bin/bash
wget http://mirror.cogentco.com/pub/apache/storm/apache-storm-1.2.1/apache-storm-1.2.1.zip
unzip apache-storm-1.2.1.zip
mkdir tmp/storm/logs -p
echo "storm.zookeeper.servers:" >> apache-storm-1.2.1/conf/storm.yaml
while IFS='' read -r line || [[ -n "$line" ]]; do
        echo "- \"$line\"" >> apache-storm-1.2.1/conf/storm.yaml
done < "$1"

echo "storm.local.dir: \"~/tmp/storm/logs\"" >>  apache-storm-1.2.1/conf/storm.yaml
echo "nimbus.seeds : [\"$2\"]" >>  apache-storm-1.2.1/conf/storm.yaml
echo "supervisor.slots.port:" >> apache-storm-1.2.1/conf/storm.yaml
for i in `seq 1 $3`;
        do
                echo "- $((6699 + i))">>apache-storm-1.2.1/conf/storm.yaml
        done

rm apache-storm-1.2.1.zip

